version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend  # Ensure backend is started before frontend

  backend:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://krishna1137:ModIApJlNNxo2GZo@mongodb:27017/test  # Use internal MongoDB connection string
    depends_on:
      - mongodb  # Ensure mongodb is started before backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: krishna1137
      MONGO_INITDB_ROOT_PASSWORD: ModIApJlNNxo2GZo
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
